FROM alpine:latest

LABEL maintainer="you@example.com"
LABEL description="Dummy Dockerfile for testing pipelines"

RUN echo "Hello from a dummy container" > /dummy.txt

CMD ["/bin/sh", "-c", "echo 'Dummy container running...'; tail -f /dev/null"]
