apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: internship-day5
spec:
  containers:
  - name: debug
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    env:
    - name: MESSAGE
      valueFrom:
        configMapKeyRef:
          name: hello-config
          key: MESSAGE
